# Generated by Django 3.2 on 2021-06-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=55)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155)),
                ('Phone', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.TextField()),
                ('ProjectType', models.IntegerField()),
                ('ProjectTheme', models.CharField(max_length=255)),
                ('ProjectStatus', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155)),
                ('TaskType', models.CharField(max_length=155)),
                ('ProjectType', models.IntegerField()),
                ('ShortTask', models.CharField(max_length=155)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('ProjectLink', models.CharField(max_length=255)),
                ('Photos', models.JSONField()),
            ],
        ),
    ]
