# Generated by Django 3.2.4 on 2021-06-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_consult_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=55)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='new_project_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('phone', models.CharField(max_length=55)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comment', models.TextField(blank=True)),
                ('project_type', models.IntegerField(blank=True)),
                ('project_theme', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=55)),
            ],
        ),
        migrations.DeleteModel(
            name='NewConsultRequest',
        ),
        migrations.DeleteModel(
            name='NewProjectRequest',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='CreateDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Photos',
            new_name='photos',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectLink',
            new_name='project_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectType',
            new_name='project_type',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ShortTask',
            new_name='short_task',
        ),
        migrations.RemoveField(
            model_name='project',
            name='TaskType',
        ),
    ]
