# Generated by Django 3.2 on 2021-04-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newprojectrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(max_length=55)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
