# Generated by Django 3.2 on 2021-04-19 17:01

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155)),
                ('TaskType', models.CharField(max_length=155)),
                ('ProjectType', models.IntegerField()),
                ('ShortTask', models.CharField(max_length=155)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField()),
                ('ProjectLink', models.CharField(max_length=255)),
                ('Photos', models.JSONField(default=news.models.get_default_from_photos)),
            ],
        ),
    ]
