# Generated by Django 3.2 on 2021-04-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=155)),
                ('Phone', models.CharField(max_length=55)),
                ('Email', models.EmailField(max_length=254)),
                ('Comment', models.TextField()),
                ('ProjectType', models.IntegerField()),
                ('ProjectTheme', models.CharField(max_length=255)),
                ('ProjectStatus', models.CharField(max_length=55)),
            ],
        ),
    ]
