# Generated by Django 3.2 on 2021-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newconsultrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Photos',
            field=models.JSONField(verbose_name='Photos'),
        ),
    ]
