# Generated by Django 3.2 on 2021-06-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_rename_url_hash_value_url_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='clicks',
            new_name='redirects',
        ),
    ]
