# Generated by Django 3.2 on 2021-06-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0004_rename_clicks_url_redirects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
