# Generated by Django 3.2 on 2021-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_alter_url_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
