# Generated by Django 3.2 on 2021-06-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0006_alter_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url_hash',
            name='ip',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
