# Generated by Django 3.2 on 2021-06-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0007_url_hash_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url_hash',
            old_name='date_use',
            new_name='time',
        ),
    ]
